[www]
user = ${SUPERVISOR_PHP_USER}
group = ${SUPERVISOR_PHP_USER}
listen = 127.0.0.1:9000

pm = dynamic
pm.max_children = 3
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 2
pm.max_requests = 500

clear_env = no
catch_workers_output = yes
decorate_workers_output = no
